import React from 'react'

export default function Footer() {
    return (
        <div>
            Footer
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit officia quae voluptates temporibus ab doloremque similique cumque rerum vel et excepturi animi quisquam dignissimos eum perspiciatis adipisci aut enim, iste placeat ex eveniet labore. Mollitia, molestias voluptas quod illo reiciendis sapiente numquam ab deserunt, ut explicabo, pariatur rem incidunt itaque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed exercitationem eius mollitia hic nisi neque rem praesentium quisquam? Vel minus pariatur sunt ullam, accusantium placeat cupiditate natus temporibus possimus molestiae porro perspiciatis et praesentium aspernatur neque quae impedit, tempore explicabo beatae esse rem cum ducimus alias ipsa! Nam, velit id exercitationem perspiciatis itaque officia pariatur nisi quae, adipisci, maiores modi dicta aperiam ab! Culpa neque nobis eum. Facere nobis architecto adipisci minima impedit neque delectus numquam quia temporibus ipsa dicta nisi assumenda, pariatur voluptatibus, accusamus dolorem debitis esse consequuntur voluptas sed doloremque fugiat vitae! Totam explicabo dolorum vero nihil, fugit beatae. Doloremque, repudiandae, a repellendus reprehenderit perspiciatis velit cumque deleniti esse eveniet hic laudantium voluptatum! Voluptatem quasi quis nisi vel! Vero ipsam aspernatur dolores qui. Aliquid aut dolore reprehenderit cupiditate quaerat praesentium aliquam, sapiente laudantium illum ipsa excepturi debitis sint quidem fugit recusandae deleniti. Aliquid adipisci, maxime earum ad officiis magnam officia, vel, iste possimus quo sequi culpa esse repellat mollitia illum provident reprehenderit quisquam. Neque repellat labore fugit distinctio impedit modi! Rem ullam totam eum non velit adipisci voluptatem. Magni, similique sint? Commodi molestias, laboriosam odio labore doloribus assumenda vero, incidunt eaque nam tempore expedita ducimus dignissimos adipisci quisquam laudantium deleniti sit rerum perspiciatis ab. Eveniet accusamus perspiciatis hic veritatis alias ipsam unde sequi expedita soluta quae impedit molestiae inventore dolores eligendi, odit ea quam et tenetur corrupti magni dolor tempore. Perspiciatis dolorum nemo voluptate quas ducimus quae, quibusdam quidem nesciunt, esse facilis quod qui? Quisquam, atque consequatur a laudantium error nulla eaque provident nihil nobis, ullam, ducimus animi mollitia vitae? Nemo doloremque quas soluta itaque voluptas cumque explicabo pr
        </div>
    )
}
